plugins {
    id "com.gradleup.shadow" version "9.4.1"
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

repositories {
    maven { url = "https://maven.terraformersmc.com/" }
    maven { url = "https://maven.shedaniel.me/" }
    mavenCentral()
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    common(project(path: ":common", configuration: "default")) { transitive = false }
    shadowCommon(project(path: ":common", configuration: "default")) { transitive = false }

    implementation "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_version}", {
        exclude module: 'fabric-api'
    }

    compileOnly "com.terraformersmc:modmenu:${project.modmenu_version}", {
        exclude module: 'fabric-api'
    }

    implementation(fabricApi.module("fabric-resource-loader-v1", project.fabric_api_version))

    implementation 'com.electronwill.night-config:json:3.6.6'
    shadowCommon 'com.electronwill.night-config:json:3.6.6'
    compileOnly "com.google.code.findbugs:jsr305:3.0.2"
}

processResources {
    def modVersion = project.version.toString()
    inputs.property "version", modVersion

    filesMatching("fabric.mod.json") {
        expand "version": modVersion
    }
}

shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set("Fabric-${rootProject.minecraft_version}")
    relocate 'com.electronwill.nightconfig', 'me.cominixo.betterf3.libs.nightconfig'
    from rootProject.file("LICENSE.txt")
}

jar {
    archiveClassifier.set("dev")
}

java {
    withSourcesJar()
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from commonSources.archiveFile.map { zipTree(it) }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

unifiedPublishing {
    project {
        displayName.set("BetterF3 Fabric v${project.version} (${project.supported_minecraft_versions})")
        version = project.version
        changelog = releaseChangelog()
        releaseType.set(project.releaseType)
        List<String> mcVersions = project.supported_minecraft_versions_list.split(",")
        gameVersions.set(mcVersions)
        gameLoaders = ["fabric", "quilt"]

        mainPublication(tasks.shadowJar)

        relations {
            depends {
                curseforge.set "cloth-config"
                modrinth.set "cloth-config"
            }
            depends {
                curseforge.set "fabric-api"
                modrinth.set "fabric-api"
            }
            optional {
                curseforge.set "modmenu"
                modrinth.set "modmenu"
            }
        }

        var CURSE_API_KEY = project.findProperty("CURSE_API_KEY") ?: System.getenv("CURSE_API_KEY")
        if (CURSE_API_KEY != null && CURSE_API_KEY instanceof String) {
            curseforge {
                token.set(CURSE_API_KEY)
                id = rootProject.curseforge_id
                gameVersions.addAll("Java 25", "Client")
            }
        }

        var MODRINTH_TOKEN = project.findProperty("MODRINTH_TOKEN") ?: System.getenv("MODRINTH_TOKEN")
        if (MODRINTH_TOKEN != null && MODRINTH_TOKEN instanceof String) {
            modrinth {
                token.set(MODRINTH_TOKEN)
                id = rootProject.modrinth_id
            }
        }
    }
}
