# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

archives_base_name=BetterF3

minecraft_version=1.21.7
supported_minecraft_versions=1.21.7
supported_minecraft_versions_list=1.21.7

mod_version=16.0.0
releaseType=release
maven_group=me.treyruffy.betterf3

platforms=fabric,neoforge

fabric_loader_version=0.16.14
fabric_api_version=0.129.0+1.21.7

cloth_version=19.0.147
modmenu_version=15.0.0-beta.3

neoforge_version=21.7.17-beta

modrinth_id=8shC1gFX
curseforge_id=401648
