# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

archives_base_name=BetterF3

minecraft_version=26.3
supported_minecraft_versions=26.3
supported_minecraft_versions_list=26.3

mod_version=20.0.0
releaseType=release
maven_group=me.treyruffy.betterf3

platforms=fabric,neoforge

fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3

cloth_version=26.3.159
modmenu_version=21.0.0

neoforge_version=26.3.0.26-beta

modrinth_id=8shC1gFX
curseforge_id=401648
