# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

archives_base_name=BetterF3

minecraft_version=26.1
supported_minecraft_versions=26.1-26.1.2
supported_minecraft_versions_list=26.1,26.1.1,26.1.2

mod_version=18.0.2
releaseType=release
maven_group=me.treyruffy.betterf3

platforms=fabric,neoforge

fabric_loader_version=0.19.2
fabric_api_version=0.145.1+26.1

cloth_version=26.1.154
modmenu_version=18.0.0-alpha.8

neoforge_version=26.1.0.19-beta

modrinth_id=8shC1gFX
curseforge_id=401648
